export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';

export const ADD_ASYNC_TODO_START = 'ADD_ASYNC_TODO_START';
export const ADD_ASYNC_TODO_SUCCESS = 'ADD_ASYNC_TODO_SUCCESS';
export const ADD_ASYNC_TODO_FAILURE = 'ADD_ASYNC_TODO_FAILURE';

export const GET_ASYNC_ALL_TODOS_START = 'GET_ASYNC_ALL_TODOS_START';
export const GET_ASYNC_ALL_TODOS_FINISH = 'GET_ASYNC_ALL_TODOS_FINISH';
export const GET_ASYNC_ALL_TODOS_SUCCESS = 'GET_ASYNC_ALL_TODOS_SUCCESS';
export const GET_ASYNC_ALL_TODOS_FAILURE = 'GET_ASYNC_ALL_TODOS_FAILURE';

export const DELETE_ASYNC_TODO_START = 'DELETE_ASYNC_TODO_START';
export const DELETE_ASYNC_TODO_SUCCESS = 'DELETE_ASYNC_TODO_SUCCESS';
export const DELETE_ASYNC_TODO_FAILURE = 'DELETE_ASYNC_TODO_FAILURE';

